# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test Go Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-test-cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Check Build
      run: go build -v ./...

    - name: Run Tests
      run: go test -v ./...

    - name: Generate Test Coverage
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: Upload coverage artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: go-coverage-${{ github.run_number }}
        path: cover.out
        if-no-files-found: error

    - name: Vulnerability Check
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
